//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iuchat
{
    using System;
    using System.Collections.Generic;
    
    public partial class chats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public chats()
        {
            this.mensajes = new HashSet<mensajes>();
        }
    
        public int id_chat { get; set; }
        public Nullable<int> user_1 { get; set; }
        public Nullable<int> user_2 { get; set; }
        public string perfil { get; set; }
        public string receptor { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mensajes> mensajes { get; set; }
    }
}
