//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iuchat
{
    using System;
    using System.Collections.Generic;
    
    public partial class publicacion
    {
        public int id_publicacion { get; set; }
        public Nullable<int> user_publicacion { get; set; }
        public string titulo { get; set; }
        public string contenido { get; set; }
        public string foto { get; set; }
        public string hora { get; set; }
        public string fecha { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
